import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/layout/footer";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Portfolio | Andreas Takvam | Software Engineer | Bergen, Norway",
    description: "Generated by create next app, tailwindcss, and typescript.",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='no'>
            <body className='min-h-screen bg-stone-50 text-stone-900'>
                <div className='flex min-h-screen flex-col'>
                    <main className='flex-1'>{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
