import type { Metadata } from "next";
import { Manrope, Work_Sans } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/layout/footer";

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
});
const workSans = Work_Sans({
    variable: "--font-work-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Portfolio | Andreas Takvam | Software Engineer | Bergen, Norway",
    description: "Generated by create next app, tailwindcss, and typescript.",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='no'>
            <body
                className={`${workSans.variable} ${manrope.variable} min-h-screen bg-stone-50 text-stone-900`}
            >
                <div className='flex min-h-screen flex-col'>
                    <main className='flex-1'>{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
